$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/v3/bundled/config/document.json
resources:
  - name: Install MyScoop Package Manager
    type: MyCompany.Installer/MyScoop
    properties:
      name: Scoop
      ensure: Present
    dependsOn: []
  # - name: Scoop Package - act
  #   type: MyCompany.Packages/ScoopPackage
  #   properties:
  #     packageName: act
  #     ensure: Present
