$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/v3/bundled/config/document.json
resources:
  - name: Scoop Bucket - versions
    type: MyCompany.Installer/MyScoopBucket
    properties:
      name: versions
      ensure: Present
  # - name: Scoop Package - dotnet3-sdk
  #   type: MyCompany.Packages/ScoopPackage
  #   properties:
  #     packageName: dotnet3-sdk
  #     ensure: Present
  #     version: latest
  #     dependsOn: -"[resourceId('MyCompany.Installer/MyScoopBucket', 'Scoop Bucket - versions')]"

  # - name: InstallPowerBI
  #   type: Microsoft.DSC/PowerShell
  #   properties:
  #     resources:
  #       - name: Microsoft.PowerBI
  #         type: Microsoft.WinGet.DSC/WinGetPackage
  #         properties:
  #           Id: Microsoft.PowerBI
  #           Ensure: Present

  # - name: WinGetPackage - Fork.Fork
  #   type: Microsoft.WinGet.DSC
  #   properties:
  #     Id: Fork.Fork

  # - name: VSComponents
  #   type: Microsoft.DSC/PowerShell
  #   properties:
  #     resources:
  #       - name: InstallEnterpriseComponents
  #         type: Microsoft.VisualStudio.DSC/VSComponents
  #         properties:
  #           productId: Microsoft.VisualStudio.Product.Enterprise
  #           vsConfigFile: 'C:\WaC\resources\visual-studio\enterprise.vsconfig'
  #           includeRecommended: true
  #           channelId: VisualStudio.17.Release

  # - name: VSComponents
  #   type: Microsoft.VisualStudio.DSC
  #   properties:
  #     includeRecommended: true
  #     productId: Microsoft.VisualStudio.Product.Enterprise
  #     vsConfigFile: C:\WaC\resources\visual-studio\enterprise.vsconfig
  #     channelId: VisualStudio.17.Release
