$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/v3/bundled/config/document.json
resources:
  - name: MyChocolatey
    type: MyCompany.Installer/MyChocolatey
    properties:
      name: Chocolatey
      ensure: Present
  - name: MyChocolateyPackage - 7zip
    type: MyCompany.Packages/ChocolateyPackage
    properties:
      packageName: 7zip
      ensure: Present
      version: latest
